In [320]:
import warnings
import pandas as pd
import seaborn as sns
import plotly.express as px
import geopandas as gpd
import folium
import rasterio
from folium.plugins import HeatMap
import geopandas as gp
from shapely.geometry import LineString
from shapely.geometry import MultiPoint, MultiPolygon
import matplotlib.pyplot as plt
from IPython.display import display, Latex

#warnings.filterwarnings("ignore")
warnings.simplefilter(action="ignore", category=FutureWarning)

In [95]:
distritos = gpd.read_file('data/distritos/DISTRITOS_inei_geogpsperu_suyopomalia.shp')
provincia = gpd.read_file('data/provincias/PROVINCIAS_inei_geogpsperu_suyopomalia.shp')

In [22]:
distritos.head()

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,POBTOTAL,POB_EDAD_T,POB_EDAD_E,DENSIDAD,...,MUJERES__3,HOMBRES_NA,HOMBRES__2,TOTAL_NACI,IND_121951,IND_122042,IND_122047,IND_516462,IND_516484,geometry
0,100902,1.0,HUANUCO,PUERTO INCA,CODO DEL POZUZO,CODO DEL POZUZO,7768.0,5022.0,4329.0,2.338322,...,96.0,53.846154,112.0,208.0,37.0,11868.28878,9469.69031,75000.0,730.0,"POLYGON ((-75.31797 -9.29529, -75.31710 -9.297..."
1,100904,2.0,HUANUCO,PUERTO INCA,TOURNAVISTA,TOURNAVISTA,6219.0,4162.0,3577.0,2.790716,...,63.0,51.908397,68.0,131.0,35.0,7746.84703,6279.18003,13500.0,1236.0,"POLYGON ((-75.20831 -9.10175, -75.20805 -9.101..."
2,250305,3.0,UCAYALI,PADRE ABAD,ALEXANDER VON HUMBOLDT,ALEXANDER VON HUMBOLDT,6085.0,4172.0,3616.0,31.892034,...,40.0,50.617284,41.0,81.0,53.0,3892.91357,3316.87044,43950.0,540.0,"POLYGON ((-74.95635 -8.79148, -74.95612 -8.792..."
3,250302,4.0,UCAYALI,PADRE ABAD,IRAZOLA,SAN ALEJANDRO,10941.0,7308.0,6368.0,10.952719,...,156.0,52.000000,169.0,325.0,176.0,11690.84202,11225.28471,125760.0,1366.0,"POLYGON ((-75.10843 -8.79990, -75.11753 -8.812..."
4,250304,5.0,UCAYALI,PADRE ABAD,NESHUYA,MONTE ALEGRE,9003.0,5983.0,5058.0,15.535539,...,0.0,0.000000,0.0,0.0,60.0,7432.20148,6834.75852,237441.0,691.0,"POLYGON ((-75.01589 -8.44637, -75.01585 -8.446..."

In [23]:
distritos['centroid'] = distritos.centroid
distritos.head(2)

/tmp/ipykernel_22071/1312048090.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  distritos['centroid'] = distritos.centroid

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,POBTOTAL,POB_EDAD_T,POB_EDAD_E,DENSIDAD,...,HOMBRES_NA,HOMBRES__2,TOTAL_NACI,IND_121951,IND_122042,IND_122047,IND_516462,IND_516484,geometry,centroid
0,100902,1.0,HUANUCO,PUERTO INCA,CODO DEL POZUZO,CODO DEL POZUZO,7768.0,5022.0,4329.0,2.338322,...,53.846154,112.0,208.0,37.0,11868.28878,9469.69031,75000.0,730.0,"POLYGON ((-75.31797 -9.29529, -75.31710 -9.297...",POINT (-75.46654 -9.63436)
1,100904,2.0,HUANUCO,PUERTO INCA,TOURNAVISTA,TOURNAVISTA,6219.0,4162.0,3577.0,2.790716,...,51.908397,68.0,131.0,35.0,7746.84703,6279.18003,13500.0,1236.0,"POLYGON ((-75.20831 -9.10175, -75.20805 -9.101...",POINT (-74.86638 -9.00132)

In [ ]:
distritos['centroid'] = distritos.centroid
distritos.head(2)

In [96]:
provincia['lat_cent'] = provincia.centroid.y
provincia['lon_cent'] = provincia.centroid.x

/tmp/ipykernel_22071/277552241.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  provincia['lat_cent'] = provincia.centroid.y
/tmp/ipykernel_22071/277552241.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  provincia['lon_cent'] = provincia.centroid.x

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,POBTOTAL,POB_EDAD_T,POB_EDAD_E,DENSIDAD,...,MUJERES__3,HOMBRES_NA,HOMBRES__2,TOTAL_NACI,IND_121951,IND_122042,IND_122047,IND_516462,IND_516484,geometry
0,100902,1.0,HUANUCO,PUERTO INCA,CODO DEL POZUZO,CODO DEL POZUZO,7768.0,5022.0,4329.0,2.338322,...,96.0,53.846154,112.0,208.0,37.0,11868.28878,9469.69031,75000.0,730.0,"POLYGON ((-75.31797 -9.29529, -75.31710 -9.297..."
1,100904,2.0,HUANUCO,PUERTO INCA,TOURNAVISTA,TOURNAVISTA,6219.0,4162.0,3577.0,2.790716,...,63.0,51.908397,68.0,131.0,35.0,7746.84703,6279.18003,13500.0,1236.0,"POLYGON ((-75.20831 -9.10175, -75.20805 -9.101..."

In [97]:
provincia.head(2)

,OBJECTID,NOMBDEP,IDPROV,CCPP,CCDD,NOMBPROV,FUENTE,POB_PROYEC,POBTOTAL,POB_EDAD_T,...,IND_122047,IND_516462,IND_516484,Shape_Leng,Shape_Area,Shape_Le_1,Shape_Ar_1,geometry,lat_cent,lon_cent
0,1.0,AMAZONAS,0101,01,01,CHACHAPOYAS,INEI - CPV2017,63188.0,60419.0,45859.0,...,57822.17436,994587.0,3403.0,4.623216,1.700899,3.861441,0.23771,"POLYGON ((-77.72614 -5.94354, -77.72486 -5.943...",-6.437059,-77.773167
1,2.0,AMAZONAS,0102,02,01,BAGUA,INEI - CPV2017,84672.0,82193.0,56236.0,...,43717.28502,608750.0,6191.0,0.000000,0.000000,4.294735,0.47236,"POLYGON ((-78.61909 -4.51001, -78.61802 -4.510...",-5.087450,-78.402692

In [98]:
provincia['NOMBPROV'] = distritos['NOMBPROV'].apply(lambda x: str(x).lower()) 
provincia['NOMBDEP'] = distritos['NOMBDEP'].apply(lambda x: str(x).lower()) 
provincia.head(2)

,OBJECTID,NOMBDEP,IDPROV,CCPP,CCDD,NOMBPROV,FUENTE,POB_PROYEC,POBTOTAL,POB_EDAD_T,...,IND_122047,IND_516462,IND_516484,Shape_Leng,Shape_Area,Shape_Le_1,Shape_Ar_1,geometry,lat_cent,lon_cent
0,1.0,huanuco,0101,01,01,puerto inca,INEI - CPV2017,63188.0,60419.0,45859.0,...,57822.17436,994587.0,3403.0,4.623216,1.700899,3.861441,0.23771,"POLYGON ((-77.72614 -5.94354, -77.72486 -5.943...",-6.437059,-77.773167
1,2.0,huanuco,0102,02,01,puerto inca,INEI - CPV2017,84672.0,82193.0,56236.0,...,43717.28502,608750.0,6191.0,0.000000,0.000000,4.294735,0.47236,"POLYGON ((-78.61909 -4.51001, -78.61802 -4.510...",-5.087450,-78.402692

In [25]:
distritos['NOMBDIST'] = distritos['NOMBDIST'].apply(lambda x: str(x).lower()) 
distritos['NOMBDEP'] = distritos['NOMBDEP'].apply(lambda x: str(x).lower()) 
distritos['NOMBPROV'] = distritos['NOMBPROV'].apply(lambda x: str(x).lower())
distritos.head(2)

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,POBTOTAL,POB_EDAD_T,POB_EDAD_E,DENSIDAD,...,TOTAL_NACI,IND_121951,IND_122042,IND_122047,IND_516462,IND_516484,geometry,centroid,lat_cent,lon_cent
0,100902,1.0,huanuco,puerto inca,codo del pozuzo,CODO DEL POZUZO,7768.0,5022.0,4329.0,2.338322,...,208.0,37.0,11868.28878,9469.69031,75000.0,730.0,"POLYGON ((-75.31797 -9.29529, -75.31710 -9.297...",POINT (-75.46654 -9.63436),-9.634364,-75.466540
1,100904,2.0,huanuco,puerto inca,tournavista,TOURNAVISTA,6219.0,4162.0,3577.0,2.790716,...,131.0,35.0,7746.84703,6279.18003,13500.0,1236.0,"POLYGON ((-75.20831 -9.10175, -75.20805 -9.101...",POINT (-74.86638 -9.00132),-9.001319,-74.866385

In [34]:
dist_sh = list(distritos['NOMBDIST'].unique())
dist_sh
type(dist_sh), len(dist_sh)

(list, 1722)

In [215]:
df = pd.read_excel('data/dataset_tasacion_train_vf.xlsx',
                  dtype = { # indicate categorical variables
                            #'Tipo de vía': 'category',
                            #'Piso': 'category',
                            #'Departamento': 'category',
                            #'Provincia': 'category',
                            #'Distrito': 'category',
                            #'Categoría del bien': 'category',
                            #'Posición': 'category',
                            #'Estado de conservación': 'category',
                            #'Método Representado': 'category'
                            #,'Área Terreno': np.float64,
                            #'Área Construcción': np.float64
                                

                            }
                  )

In [216]:
df['Área Terreno'] = df['Área Terreno'].apply(lambda x: str(x).replace(',', '')) 
df['Área Construcción'] = df['Área Construcción'].apply(lambda x: str(x).replace(',', '')) 
df['Área Terreno'] = pd.to_numeric(df['Área Terreno'], errors='coerce')
df['Área Construcción'] = pd.to_numeric(df['Área Construcción'], errors='coerce')

In [217]:
df.head()

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,2020-02-16,1.0,NaN,Piura,Piura,Veintiseis de Octubre,NaN,NaN,-5.163182,-80.682388,Vivienda Unifamiliar,NaN,NaN,0.0,NaN,En construcción,Costos o reposición (directo),62.50,27.58,25278
1,2019-05-21,1.0,NaN,Lima,Lima,Surquillo,1.0,0.0,-12.115286,-77.003768,Departamento,NaN,NaN,1.0,NaN,Bueno,Comparación de mercado (directo),9.32,57.47,110807
2,2020-04-11,1.0,NaN,Junín,Satipo,Satipo,0.0,0.0,-11.235446,-74.629221,Vivienda Unifamiliar,NaN,NaN,7.0,NaN,Regular,Costos o reposición (directo),126.00,84.00,42285
3,2016-05-24,1.0,NaN,Lima,Lima,Santiago de Surco,0.0,0.0,-12.126384,-76.975707,Oficina,NaN,NaN,0.0,NaN,NaN,Comparación de mercado (directo),8.60,82.34,165503
4,2016-01-12,3.0,NaN,Lima,Lima,Lima,0.0,0.0,-12.089613,-76.994475,Vivienda Unifamiliar,NaN,NaN,43.0,NaN,NaN,Comparación de mercado (directo),357.55,423.22,711009

In [218]:
df['Departamento'] = df['Departamento'].apply(lambda x: str(x).lower()) 
df['Provincia'] = df['Provincia'].apply(lambda x: str(x).lower()) 
df['Distrito'] = df['Distrito'].apply(lambda x: str(x).lower())
df.head(2)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,2020-02-16,1.0,NaN,piura,piura,veintiseis de octubre,NaN,NaN,-5.163182,-80.682388,Vivienda Unifamiliar,NaN,NaN,0.0,NaN,En construcción,Costos o reposición (directo),62.50,27.58,25278
1,2019-05-21,1.0,NaN,lima,lima,surquillo,1.0,0.0,-12.115286,-77.003768,Departamento,NaN,NaN,1.0,NaN,Bueno,Comparación de mercado (directo),9.32,57.47,110807

In [219]:
import unicodedata
def strip_accents(s):
   return ''.join(c for c in unicodedata.normalize('NFD', s)
                  if unicodedata.category(c) != 'Mn')

In [220]:
df['Departamento'] = df['Departamento'].apply(strip_accents) 
df['Provincia'] = df['Provincia'].apply(strip_accents) 
df['Distrito'] = df['Distrito'].apply(strip_accents)
df.head(2)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,2020-02-16,1.0,NaN,piura,piura,veintiseis de octubre,NaN,NaN,-5.163182,-80.682388,Vivienda Unifamiliar,NaN,NaN,0.0,NaN,En construcción,Costos o reposición (directo),62.50,27.58,25278
1,2019-05-21,1.0,NaN,lima,lima,surquillo,1.0,0.0,-12.115286,-77.003768,Departamento,NaN,NaN,1.0,NaN,Bueno,Comparación de mercado (directo),9.32,57.47,110807

In [198]:
dist_df = list(df['Distrito'].unique())

In [156]:
type(dist_df), len(dist_df)

(list, 475)

In [46]:
dist_df_set = set(dist_df)
dist_sh_set = set(dist_sh)
diff_set = dist_df_set - dist_sh_set
diff_set

{'alto amazonas',
 'brena',
 'chincha',
 'encanada',
 'ferrenafe',
 'inapari',
 'kosnipata',
 'los banos del inca',
 'nazca',
 'nepena',
 'ocona',
 'parinas',
 'raymondi',
 'san vicente de canete',
 'sana'}

In [48]:
distritos.columns

Index(['UBIGEO', 'OBJECTID', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST', 'CAPITAL',
       'POBTOTAL', 'POB_EDAD_T', 'POB_EDAD_E', 'DENSIDAD', 'POBMASCU',
       'POBFEMEN', 'POBMASCU_P', 'POBFEMEN_P', 'R_MASCULIN', 'POBURBANA',
       'POBRURAL', 'POBURBANA_', 'POBRURAL_P', 'EDAD_PROME', 'POB_0_14',
       'POB_15_29', 'POB_30_59', 'POB_60_MAS', 'VIV_PARTIC', 'VIV_PART_1',
       'HOGARES', 'Shape_Leng', 'Shape_Area', 'DIRECCION', 'POB_PROYEC',
       'POB_EDAD_1', 'POB_EDAD_2', 'EDAD_MEDIA', 'POB_0_14_P', 'POB_15_29_',
       'POB_30_59_', 'POB_60_M_1', 'POB_ANALFA', 'POB_ANAL_1', 'HOMBRES_AN',
       'HOMBRES__1', 'MUJERES_AN', 'MUJERES__1', 'MUJERES_ED', 'MUJERES__2',
       'TOTAL_MADR', 'MADRES_SOL', 'MADRES_S_1', 'MUJERES_AD', 'MADRES_ADO',
       'MADRES_A_1', 'AL_MENOS_1', 'AL_MENOS_2', 'SIN_DISCAP', 'SIN_DISC_1',
       'ALGUNA_NBI', 'NBI_PORC', 'VIV_PART_2', 'IC_INF', 'IC_SUP',
       'UBIC_POBMO', 'TOTAL_DEFU', 'TOTAL_DE_1', 'TOTAL_DE_2', 'NAC_BAJOPE',
       'NAC_BAJO_1', 'MUJERES_NA', 'MUJERES__3', 'HOMBRES_NA', 'HOMBRES__2',
       'TOTAL_NACI', 'IND_121951', 'IND_122042', 'IND_122047', 'IND_516462',
       'IND_516484', 'geometry', 'centroid', 'lat_cent', 'lon_cent'],
      dtype='object')

In [52]:
distritos_cent = distritos[['UBIGEO', 'OBJECTID', 'NOMBDEP', 'NOMBPROV', 'NOMBDIST', 'CAPITAL', 'lat_cent', 'lon_cent']]

In [53]:
distritos_cent.head()

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,lat_cent,lon_cent
0,100902,1.0,huanuco,puerto inca,codo del pozuzo,CODO DEL POZUZO,-9.634364,-75.466540
1,100904,2.0,huanuco,puerto inca,tournavista,TOURNAVISTA,-9.001319,-74.866385
2,250305,3.0,ucayali,padre abad,alexander von humboldt,ALEXANDER VON HUMBOLDT,-8.824928,-75.048021
3,250302,4.0,ucayali,padre abad,irazola,SAN ALEJANDRO,-8.950516,-75.279918
4,250304,5.0,ucayali,padre abad,neshuya,MONTE ALEGRE,-8.641299,-75.049031

In [56]:
distritos_cent.to_parquet('data/distritos_cent.parquet.gzip',
              compression='gzip')

In [101]:
provincia.head(2)

,OBJECTID,NOMBDEP,IDPROV,CCPP,CCDD,NOMBPROV,FUENTE,POB_PROYEC,POBTOTAL,POB_EDAD_T,...,IND_122047,IND_516462,IND_516484,Shape_Leng,Shape_Area,Shape_Le_1,Shape_Ar_1,geometry,lat_cent,lon_cent
0,1.0,huanuco,0101,01,01,puerto inca,INEI - CPV2017,63188.0,60419.0,45859.0,...,57822.17436,994587.0,3403.0,4.623216,1.700899,3.861441,0.23771,"POLYGON ((-77.72614 -5.94354, -77.72486 -5.943...",-6.437059,-77.773167
1,2.0,huanuco,0102,02,01,puerto inca,INEI - CPV2017,84672.0,82193.0,56236.0,...,43717.28502,608750.0,6191.0,0.000000,0.000000,4.294735,0.47236,"POLYGON ((-78.61909 -4.51001, -78.61802 -4.510...",-5.087450,-78.402692

In [103]:
provincia_cent = provincia[['OBJECTID', 'NOMBDEP', 'NOMBPROV', 'lat_cent', 'lon_cent']]

In [104]:
provincia_cent.head(2)

   OBJECTID  NOMBDEP     NOMBPROV  lat_cent   lon_cent
0       1.0  huanuco  puerto inca -6.437059 -77.773167
1       2.0  huanuco  puerto inca -5.087450 -78.402692

In [105]:
provincia_cent.to_parquet('data/provincia_cent.parquet.gzip',
              compression='gzip')

In [49]:
distritos.head()

,UBIGEO,OBJECTID,NOMBDEP,NOMBPROV,NOMBDIST,CAPITAL,POBTOTAL,POB_EDAD_T,POB_EDAD_E,DENSIDAD,...,TOTAL_NACI,IND_121951,IND_122042,IND_122047,IND_516462,IND_516484,geometry,centroid,lat_cent,lon_cent
0,100902,1.0,huanuco,puerto inca,codo del pozuzo,CODO DEL POZUZO,7768.0,5022.0,4329.0,2.338322,...,208.0,37.0,11868.28878,9469.69031,75000.0,730.0,"POLYGON ((-75.31797 -9.29529, -75.31710 -9.297...",POINT (-75.46654 -9.63436),-9.634364,-75.466540
1,100904,2.0,huanuco,puerto inca,tournavista,TOURNAVISTA,6219.0,4162.0,3577.0,2.790716,...,131.0,35.0,7746.84703,6279.18003,13500.0,1236.0,"POLYGON ((-75.20831 -9.10175, -75.20805 -9.101...",POINT (-74.86638 -9.00132),-9.001319,-74.866385
2,250305,3.0,ucayali,padre abad,alexander von humboldt,ALEXANDER VON HUMBOLDT,6085.0,4172.0,3616.0,31.892034,...,81.0,53.0,3892.91357,3316.87044,43950.0,540.0,"POLYGON ((-74.95635 -8.79148, -74.95612 -8.792...",POINT (-75.04802 -8.82493),-8.824928,-75.048021
3,250302,4.0,ucayali,padre abad,irazola,SAN ALEJANDRO,10941.0,7308.0,6368.0,10.952719,...,325.0,176.0,11690.84202,11225.28471,125760.0,1366.0,"POLYGON ((-75.10843 -8.79990, -75.11753 -8.812...",POINT (-75.27992 -8.95052),-8.950516,-75.279918
4,250304,5.0,ucayali,padre abad,neshuya,MONTE ALEGRE,9003.0,5983.0,5058.0,15.535539,...,0.0,60.0,7432.20148,6834.75852,237441.0,691.0,"POLYGON ((-75.01589 -8.44637, -75.01585 -8.446...",POINT (-75.04903 -8.64130),-8.641299,-75.049031

In [62]:
df.isnull().sum()

Fecha entrega del Informe        0
Tipo de vía                   5011
Piso                         53233
Departamento                     0
Provincia                        0
Distrito                         0
Número de estacionamiento     7924
Depósitos                     7993
Latitud (Decimal)              863
Longitud (Decimal)             917
Categoría del bien            2449
Posición                     53141
Número de frentes            53157
Edad                          4789
Elevador                     53138
Estado de conservación       15700
Método Representado              7
Área Terreno                  1153
Área Construcción             4493
Valor comercial (USD)            0
dtype: int64

In [64]:
df[['Latitud (Decimal)', 'Longitud (Decimal)']].isnull().sum()

Latitud (Decimal)     863
Longitud (Decimal)    917
dtype: int64

In [72]:
(df['Latitud (Decimal)'].isnull() == True)

0        False
1        False
2        False
3        False
4        False
         ...
53249    False
53250    False
53251    False
53252    False
53253    False
Name: Latitud (Decimal), Length: 53254, dtype: bool

In [ ]:
(df['Longitud (Decimal)'].isnull() == True)

In [74]:
import numpy as np

In [81]:
((df['Latitud (Decimal)'].isnull() == True) | (df['Longitud (Decimal)'].isnull() == True))

0        False
1        False
2        False
3        False
4        False
         ...
53249    False
53250    False
53251    False
53252    False
53253    False
Length: 53254, dtype: bool

In [84]:
dist_coord_lost = df[((df['Latitud (Decimal)'].isnull() == True) | (df['Longitud (Decimal)'].isnull() == True)) == True]
dist_lost = list(dist_coord_lost['Distrito'].unique())
len(dist_lost)

139

In [121]:
df.columns

Index(['Fecha entrega del Informe', 'Tipo de vía', 'Piso', 'Departamento',
       'Provincia', 'Distrito', 'Número de estacionamiento', 'Depósitos',
       'Latitud (Decimal)', 'Longitud (Decimal)', 'Categoría del bien',
       'Posición', 'Número de frentes', 'Edad', 'Elevador',
       'Estado de conservación', 'Método Representado', 'Área Terreno',
       'Área Construcción', 'Valor comercial (USD)'],
      dtype='object')

In [116]:
mask_idx = list(dist_coord_lost.index)

In [120]:
df.loc[mask_idx[0], ['Latitud (Decimal)', 'Longitud (Decimal)']]

Latitud (Decimal)     NaN
Longitud (Decimal)    NaN
Name: 21, dtype: object

In [122]:
df.loc[mask_idx[0], 'Distrito']

'moyobamba'

In [126]:
df.loc[mask_idx[0], 'Distrito'] in dist_sh

True

In [174]:
(distritos_cent.loc[distritos_cent['NOMBDIST'] == 'moyobamba', 'lat_cent']).values

array([-5.76828169])

In [177]:
distrito = df.loc[i, 'Distrito']
distrito in dist_sh

False

In [176]:
(distritos_cent.loc[distritos_cent['NOMBDIST'] == distrito, 'lat_cent']).values[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [178]:
provincia = df.loc[i, 'Provincia']
provincia

'chincha'

In [188]:
provincia

'chincha'

In [187]:
prov_sh = list(provincia_cent['NOMBPROV'].unique())

In [221]:
for i in mask_idx:
    distrito = df.loc[i, 'Distrito']
    provincia = df.loc[i, 'Provincia']
    
    if distrito in dist_sh:
        df.loc[i, 'Latitud (Decimal)'] = (distritos_cent.loc[distritos_cent['NOMBDIST'] == distrito, 'lat_cent']).values[0]
        df.loc[i, 'Longitud (Decimal)'] = (distritos_cent.loc[distritos_cent['NOMBDIST'] == distrito, 'lon_cent']).values[0]
    elif provincia in prov_sh:
        df.loc[i, 'Latitud (Decimal)'] = (provincia_cent.loc[provincia_cent['NOMBPROV'] == provincia, 'lat_cent']).values[0]
        df.loc[i, 'Longitud (Decimal)'] = (provincia_cent.loc[provincia_cent['NOMBPROV'] == provincia, 'lon_cent']).values[0]
    else:
        df.loc[i, 'Latitud (Decimal)'] = -9.19
        df.loc[i, 'Longitud (Decimal)'] = -75.016

In [222]:
df.isna().sum()

Fecha entrega del Informe        0
Tipo de vía                   5011
Piso                         53233
Departamento                     0
Provincia                        0
Distrito                         0
Número de estacionamiento     7924
Depósitos                     7993
Latitud (Decimal)                0
Longitud (Decimal)               0
Categoría del bien            2449
Posición                     53141
Número de frentes            53157
Edad                          4789
Elevador                     53138
Estado de conservación       15700
Método Representado              7
Área Terreno                  1153
Área Construcción             4493
Valor comercial (USD)            0
dtype: int64

In [191]:
df.head()

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),...,"(1233, Latitud (Decimal))","(1275, Latitud (Decimal))","(1286, Latitud (Decimal))","(1292, Latitud (Decimal))","(1368, Latitud (Decimal))","(1394, Latitud (Decimal))","(1408, Latitud (Decimal))","(1539, Latitud (Decimal))","(1560, Latitud (Decimal))","(1576, Latitud (Decimal))"
0,2020-02-16,1.0,NaN,piura,piura,veintiseis de octubre,NaN,NaN,-5.163182,-80.682388,...,-76.96314,-77.110814,-75.07128,-77.048874,-78.401191,-76.87748,-77.048874,-75.07128,-77.048874,-77.473246
1,2019-05-21,1.0,NaN,lima,lima,surquillo,1.0,0.0,-12.115286,-77.003768,...,-76.96314,-77.110814,-75.07128,-77.048874,-78.401191,-76.87748,-77.048874,-75.07128,-77.048874,-77.473246
2,2020-04-11,1.0,NaN,junin,satipo,satipo,0.0,0.0,-11.235446,-74.629221,...,-76.96314,-77.110814,-75.07128,-77.048874,-78.401191,-76.87748,-77.048874,-75.07128,-77.048874,-77.473246
3,2016-05-24,1.0,NaN,lima,lima,santiago de surco,0.0,0.0,-12.126384,-76.975707,...,-76.96314,-77.110814,-75.07128,-77.048874,-78.401191,-76.87748,-77.048874,-75.07128,-77.048874,-77.473246
4,2016-01-12,3.0,NaN,lima,lima,lima,0.0,0.0,-12.089613,-76.994475,...,-76.96314,-77.110814,-75.07128,-77.048874,-78.401191,-76.87748,-77.048874,-75.07128,-77.048874,-77.473246

In [86]:
dist_lost_set = set(dist_lost)

In [87]:
dist_lost_set - dist_sh_set

{'brena', 'chincha', 'los banos del inca', 'parinas', 'san vicente de canete'}

In [90]:
df[df['Distrito'] == 'brena'].head(1)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
81,2016-01-27,2.0,NaN,lima,lima,brena,1.0,1.0,-12.055923,-77.047433,Departamento,NaN,NaN,9.0,NaN,NaN,Comparación de mercado (directo),19.08,68.65,71396

In [91]:
df[df['Distrito'] == 'chincha'].head(1)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
44,2020-03-03,1.0,NaN,huancavelica,chincha,chincha,NaN,NaN,-13.494409,-76.180851,NaN,NaN,NaN,57.0,NaN,Bueno,Costos o reposición (directo),"54,000.00",232.00,910194

In [92]:
df[df['Distrito'] == 'los banos del inca'].head(1)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
1088,2020-12-01,2.0,NaN,cajamarca,cajamarca,los banos del inca,NaN,NaN,-7.166665,-78.4675,Departamento,NaN,NaN,12.0,NaN,Bueno,Comparación de mercado (directo),21.89,95.17,86604

In [93]:
df[df['Distrito'] == 'parinas'].head(1)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
1778,2019-11-12,1.0,NaN,piura,talara,parinas,NaN,NaN,NaN,NaN,AVALUOS_TIPOS_INMUEBLE_VEHICULO,NaN,NaN,NaN,NaN,NaN,Costos o reposición (directo),NaN,NaN,165684

In [94]:
df[df['Distrito'] == 'san vicente de canete'].head(1)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
196,2019-06-23,1.0,NaN,lima,canete,san vicente de canete,0.0,0.0,-12.585633,-76.704139,Vivienda Unifamiliar,NaN,NaN,0.0,NaN,En construcción,Comparación de mercado (directo),89.37,106.53,190409

In [202]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53254 entries, 0 to 53253
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fecha entrega del Informe  53254 non-null  datetime64[ns]
 1   Tipo de vía                48243 non-null  category
 2   Piso                       21 non-null     category
 3   Departamento               53254 non-null  category
 4   Provincia                  53254 non-null  object
 5   Distrito                   53254 non-null  object
 6   Número de estacionamiento  45330 non-null  float64
 7   Depósitos                  45261 non-null  float64
 8   Latitud (Decimal)          53254 non-null  float64
 9   Longitud (Decimal)         53254 non-null  float64
 10  Categoría del bien         50805 non-null  category
 11  Posición                   113 non-null    category
 12  Número de frentes          97 non-null     float64
 13  Edad                       48465 non-null  float64
 14  Elevador                   116 non-null    float64
 15  Estado de conservación     37554 non-null  category
 16  Método Representado        53247 non-null  category
 17  Área Terreno               52101 non-null  float64
 18  Área Construcción          48761 non-null  float64
 19  Valor comercial (USD)      53254 non-null  int64
dtypes: category(7), datetime64[ns](1), float64(9), int64(1), object(2)
memory usage: 5.6+ MB

In [223]:
df["Tipo de vía"].fillna(0, inplace = True)

In [225]:
df["Número de estacionamiento"].fillna(0, inplace = True)

In [226]:
df["Número de estacionamiento"].fillna(0, inplace = True)

In [227]:
Edad = []
for i in df["Edad"]:
  if i > 1600:
    Edad.append(2022-i)
  else:
    Edad.append(i)

In [228]:
df['Edad'] = Edad

In [229]:
df["Edad"].fillna(np.mean(df["Edad"]), inplace = True)

In [230]:
df['Categoría del bien'].fillna('Otro', inplace = True)

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53254 entries, 0 to 53253
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fecha entrega del Informe  53254 non-null  datetime64[ns]
 1   Tipo de vía                53254 non-null  float64
 2   Piso                       21 non-null     object
 3   Departamento               53254 non-null  object
 4   Provincia                  53254 non-null  object
 5   Distrito                   53254 non-null  object
 6   Número de estacionamiento  53254 non-null  float64
 7   Depósitos                  45261 non-null  float64
 8   Latitud (Decimal)          53254 non-null  float64
 9   Longitud (Decimal)         53254 non-null  float64
 10  Categoría del bien         53254 non-null  object
 11  Posición                   113 non-null    object
 12  Número de frentes          97 non-null     float64
 13  Edad                       53254 non-null  float64
 14  Elevador                   116 non-null    float64
 15  Estado de conservación     37554 non-null  object
 16  Método Representado        53247 non-null  object
 17  Área Terreno               52101 non-null  float64
 18  Área Construcción          48761 non-null  float64
 19  Valor comercial (USD)      53254 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(1), object(8)
memory usage: 8.1+ MB

In [ ]:
from sklearn import model_selection

In [274]:
df["kfold"] = -1

In [272]:
model_selection.KFold?

Init signature: model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)
Docstring:
K-Folds cross-validator

Provides train/test indices to split data in train/test sets. Split
dataset into k consecutive folds (without shuffling by default).

Each fold is then used once as a validation while the k - 1 remaining
folds form the training set.

Read more in the :ref:`User Guide <k_fold>`.

Parameters
----------
n_splits : int, default=5
    Number of folds. Must be at least 2.

    .. versionchanged:: 0.22
        ``n_splits`` default value changed from 3 to 5.

shuffle : bool, default=False
    Whether to shuffle the data before splitting into batches.
    Note that the samples within each split will not be shuffled.

random_state : int, RandomState instance or None, default=None
    When `shuffle` is True, `random_state` affects the ordering of the
    indices, which controls the randomness of each fold. Otherwise, this
    parameter has no effect.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import KFold
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([1, 2, 3, 4])
>>> kf = KFold(n_splits=2)
>>> kf.get_n_splits(X)
2
>>> print(kf)
KFold(n_splits=2, random_state=None, shuffle=False)
>>> for train_index, test_index in kf.split(X):
...     print("TRAIN:", train_index, "TEST:", test_index)
...     X_train, X_test = X[train_index], X[test_index]
...     y_train, y_test = y[train_index], y[test_index]
TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]

Notes
-----
The first ``n_samples % n_splits`` folds have size
``n_samples // n_splits + 1``, other folds have size
``n_samples // n_splits``, where ``n_samples`` is the number of samples.

Randomized CV splitters may return different results for each call of
split. You can make the results identical by setting `random_state`
to an integer.

See Also
--------
StratifiedKFold : Takes class information into account to avoid building
    folds with imbalanced class distributions (for binary or multiclass
    classification tasks).

GroupKFold : K-fold iterator variant with non-overlapping groups.

RepeatedKFold : Repeats K-Fold n times.
File:           ~/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/sklearn/model_selection/_split.py
Type:           ABCMeta
Subclasses:

In [279]:
model_selection.StratifiedKFold?

Init signature:
model_selection.StratifiedKFold(
    n_splits=5,
    *,
    shuffle=False,
    random_state=None,
)
Docstring:
Stratified K-Folds cross-validator.

Provides train/test indices to split data in train/test sets.

This cross-validation object is a variation of KFold that returns
stratified folds. The folds are made by preserving the percentage of
samples for each class.

Read more in the :ref:`User Guide <stratified_k_fold>`.

Parameters
----------
n_splits : int, default=5
    Number of folds. Must be at least 2.

    .. versionchanged:: 0.22
        ``n_splits`` default value changed from 3 to 5.

shuffle : bool, default=False
    Whether to shuffle each class's samples before splitting into batches.
    Note that the samples within each split will not be shuffled.

random_state : int, RandomState instance or None, default=None
    When `shuffle` is True, `random_state` affects the ordering of the
    indices, which controls the randomness of each fold for each class.
    Otherwise, leave `random_state` as `None`.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import StratifiedKFold
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([0, 0, 1, 1])
>>> skf = StratifiedKFold(n_splits=2)
>>> skf.get_n_splits(X, y)
2
>>> print(skf)
StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
>>> for train_index, test_index in skf.split(X, y):
...     print("TRAIN:", train_index, "TEST:", test_index)
...     X_train, X_test = X[train_index], X[test_index]
...     y_train, y_test = y[train_index], y[test_index]
TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]

Notes
-----
The implementation is designed to:

* Generate test sets such that all contain the same distribution of
  classes, or as close as possible.
* Be invariant to class label: relabelling ``y = ["Happy", "Sad"]`` to
  ``y = [1, 0]`` should not change the indices generated.
* Preserve order dependencies in the dataset ordering, when
  ``shuffle=False``: all samples from class k in some test set were
  contiguous in y, or separated in y by samples from classes other than k.
* Generate test sets where the smallest and largest differ by at most one
  sample.

.. versionchanged:: 0.22
    The previous implementation did not follow the last constraint.

See Also
--------
RepeatedStratifiedKFold : Repeats Stratified K-Fold n times.
File:           ~/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/sklearn/model_selection/_split.py
Type:           ABCMeta
Subclasses:

In [280]:
model_selection.KFold.split?

Signature: model_selection.KFold.split(self, X, y=None, groups=None)
Docstring:
Generate indices to split data into training and test set.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.

y : array-like of shape (n_samples,), default=None
    The target variable for supervised learning problems.

groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set.

Yields
------
train : ndarray
    The training set indices for that split.

test : ndarray
    The testing set indices for that split.
File:      ~/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/sklearn/model_selection/_split.py
Type:      function

In [282]:
kf = model_selection.KFold(n_splits=5, shuffle=True, random_state=42)
for fold, (train_indicies, valid_indicies) in enumerate(kf.split(X=df, groups=df['Provincia'])):
    df.loc[valid_indicies, "kfold"] = fold

In [283]:
df.to_csv("train_folds.csv", index=False)

In [237]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor

In [239]:
target = 'Valor comercial (USD)'

In [284]:
useful_features = [c for c in df.columns if c not in ("Valor comercial (USD)", "kfold")]
object_cols = [col for col in useful_features if 'cat' in col]

In [ ]:
object_cols = [col for col in useful_features if col.dtype

In [245]:
df.fillna(0)

,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),...,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD),kfold
0,2020-02-16,1.0,0,piura,piura,veintiseis de octubre,0.0,0.0,-5.163182,-80.682388,...,0,0.0,0.0,0.0,En construcción,Costos o reposición (directo),62.50,27.58,25278,1
1,2019-05-21,1.0,0,lima,lima,surquillo,1.0,0.0,-12.115286,-77.003768,...,0,0.0,1.0,0.0,Bueno,Comparación de mercado (directo),9.32,57.47,110807,1
2,2020-04-11,1.0,0,junin,satipo,satipo,0.0,0.0,-11.235446,-74.629221,...,0,0.0,7.0,0.0,Regular,Costos o reposición (directo),126.00,84.00,42285,4
3,2016-05-24,1.0,0,lima,lima,santiago de surco,0.0,0.0,-12.126384,-76.975707,...,0,0.0,0.0,0.0,0,Comparación de mercado (directo),8.60,82.34,165503,2
4,2016-01-12,3.0,0,lima,lima,lima,0.0,0.0,-12.089613,-76.994475,...,0,0.0,43.0,0.0,0,Comparación de mercado (directo),357.55,423.22,711009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53249,2019-07-18,1.0,0,lima,lima,santiago de surco,0.0,0.0,-12.079598,-76.976514,...,0,0.0,34.0,0.0,Bueno,Costos o reposición (directo),306.00,282.80,604241,3
53250,2017-10-22,3.0,0,lima,lima,magdalena del mar,1.0,0.0,-12.088102,-77.064252,...,0,0.0,4.0,0.0,Bueno,Comparación de mercado (directo),4.98,86.56,132721,0
53251,2021-05-31,3.0,0,lima,lima,lince,0.0,0.0,-12.087071,-77.035483,...,0,0.0,64.0,0.0,Bueno,Comparación de mercado (directo),18.63,65.77,98655,4
53252,2018-07-11,3.0,0,lima,lima,rimac,1.0,0.0,-12.030869,-77.025853,...,0,0.0,4.0,0.0,Bueno,Comparación de mercado (directo),10.08,70.15,79553,2
53253,2018-07-17,4.0,0,la libertad,trujillo,trujillo,0.0,0.0,-8.088020,-78.999926,...,0,0.0,3.0,0.0,Bueno,Costos o reposición (directo),118.40,247.70,127045,2

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53254 entries, 0 to 53253
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Fecha entrega del Informe  53254 non-null  datetime64[ns]
 1   Tipo de vía                53254 non-null  float64
 2   Piso                       21 non-null     object
 3   Departamento               53254 non-null  object
 4   Provincia                  53254 non-null  object
 5   Distrito                   53254 non-null  object
 6   Número de estacionamiento  53254 non-null  float64
 7   Depósitos                  45261 non-null  float64
 8   Latitud (Decimal)          53254 non-null  float64
 9   Longitud (Decimal)         53254 non-null  float64
 10  Categoría del bien         53254 non-null  object
 11  Posición                   113 non-null    object
 12  Número de frentes          97 non-null     float64
 13  Edad                       53254 non-null  float64
 14  Elevador                   116 non-null    float64
 15  Estado de conservación     37554 non-null  object
 16  Método Representado        53247 non-null  object
 17  Área Terreno               52101 non-null  float64
 18  Área Construcción          48761 non-null  float64
 19  Valor comercial (USD)      53254 non-null  int64
 20  kfold                      53254 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(2), object(8)
memory usage: 8.5+ MB

In [248]:
dtype0 = {'Tipo de vía': 'category',
                            'Piso': 'category',
                            'Departamento': 'category',
                            'Provincia': 'category',
                            'Distrito': 'category',
                            'Categoría del bien': 'category',
                            'Posición': 'category',
                            'Estado de conservación': 'category',
                            'Método Representado': 'category'}
df =df.astype(dtype0)

In [253]:
df['year'] = df['Fecha entrega del Informe'].dt.year
df['month'] = df['Fecha entrega del Informe'].dt.month
df.drop(columns='Fecha entrega del Informe', axis=1, inplace=True)

In [255]:
df.drop(columns='Fecha entrega del Informe', axis=1, inplace=True)

In [285]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53254 entries, 0 to 53253
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Tipo de vía                53254 non-null  category
 1   Departamento               53254 non-null  category
 2   Provincia                  53254 non-null  category
 3   Distrito                   53254 non-null  category
 4   Número de estacionamiento  53254 non-null  float64
 5   Depósitos                  45261 non-null  float64
 6   Latitud (Decimal)          53254 non-null  float64
 7   Longitud (Decimal)         53254 non-null  float64
 8   Categoría del bien         53254 non-null  category
 9   Edad                       53254 non-null  float64
 10  Elevador                   116 non-null    float64
 11  Estado de conservación     37554 non-null  category
 12  Método Representado        53247 non-null  category
 13  Área Terreno               52101 non-null  float64
 14  Área Construcción          48761 non-null  float64
 15  Valor comercial (USD)      53254 non-null  int64
 16  kfold                      53254 non-null  int64
 17  year                       53254 non-null  int64
 18  month                      53254 non-null  int64
dtypes: category(7), float64(8), int64(4)
memory usage: 5.4 MB

In [ ]:
df.drop(columns=['Piso', 'Posición', 'Número de frentes'], axis=1, inplace=True)
object_cols = ['Tipo de vía', 'Departamento', 'Provincia', 'Distrito', 'Categoría del bien', 'Estado de conservación', 'Método Representado']

In [266]:
df.drop(columns=['Piso', 'Posición', 'Número de frentes'], axis=1, inplace=True)

In [286]:
object_cols = ['Tipo de vía', 'Departamento', 'Provincia', 'Distrito', 'Categoría del bien', 'Estado de conservación', 'Método Representado']

In [293]:
OrdinalEncoder?

Init signature:
OrdinalEncoder(
    *,
    categories='auto',
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    unknown_value=None,
    encoded_missing_value=nan,
)
Docstring:
Encode categorical features as an integer array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are converted to ordinal integers. This results in
a single column of integers (0 to n_categories - 1) per feature.

Read more in the :ref:`User Guide <preprocessing_categorical_features>`.

.. versionadded:: 0.20

Parameters
----------
categories : 'auto' or a list of array-like, default='auto'
    Categories (unique values) per feature:

    - 'auto' : Determine categories automatically from the training data.
    - list : ``categories[i]`` holds the categories expected in the ith
      column. The passed categories should not mix strings and numeric
      values, and should be sorted in case of numeric values.

    The used categories can be found in the ``categories_`` attribute.

dtype : number type, default np.float64
    Desired dtype of output.

handle_unknown : {'error', 'use_encoded_value'}, default='error'
    When set to 'error' an error will be raised in case an unknown
    categorical feature is present during transform. When set to
    'use_encoded_value', the encoded value of unknown categories will be
    set to the value given for the parameter `unknown_value`. In
    :meth:`inverse_transform`, an unknown category will be denoted as None.

    .. versionadded:: 0.24

unknown_value : int or np.nan, default=None
    When the parameter handle_unknown is set to 'use_encoded_value', this
    parameter is required and will set the encoded value of unknown
    categories. It has to be distinct from the values used to encode any of
    the categories in `fit`. If set to np.nan, the `dtype` parameter must
    be a float dtype.

    .. versionadded:: 0.24

encoded_missing_value : int or np.nan, default=np.nan
    Encoded value of missing categories. If set to `np.nan`, then the `dtype`
    parameter must be a float dtype.

    .. versionadded:: 1.1

Attributes
----------
categories_ : list of arrays
    The categories of each feature determined during ``fit`` (in order of
    the features in X and corresponding with the output of ``transform``).
    This does not include categories that weren't seen during ``fit``.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 1.0

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

See Also
--------
OneHotEncoder : Performs a one-hot encoding of categorical features.
LabelEncoder : Encodes target labels with values between 0 and
    ``n_classes-1``.

Examples
--------
Given a dataset with two features, we let the encoder find the unique
values per feature and transform the data to an ordinal encoding.

>>> from sklearn.preprocessing import OrdinalEncoder
>>> enc = OrdinalEncoder()
>>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
>>> enc.fit(X)
OrdinalEncoder()
>>> enc.categories_
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
>>> enc.transform([['Female', 3], ['Male', 1]])
array([[0., 2.],
       [1., 0.]])

>>> enc.inverse_transform([[1, 0], [0, 1]])
array([['Male', 1],
       ['Female', 2]], dtype=object)

By default, :class:`OrdinalEncoder` is lenient towards missing values by
propagating them.

>>> import numpy as np
>>> X = [['Male', 1], ['Female', 3], ['Female', np.nan]]
>>> enc.fit_transform(X)
array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0., nan]])

You can use the parameter `encoded_missing_value` to encode missing values.

>>> enc.set_params(encoded_missing_value=-1).fit_transform(X)
array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0., -1.]])
File:           ~/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py
Type:           type
Subclasses:

In [303]:
from sklearn import preprocessing

In [306]:
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
numerical_cols.remove('Valor comercial (USD)')
numerical_cols

['Número de estacionamiento',
 'Depósitos',
 'Latitud (Decimal)',
 'Longitud (Decimal)',
 'Edad',
 'Elevador',
 'Área Terreno',
 'Área Construcción',
 'kfold',
 'year',
 'month']

In [309]:
df.head(2)

,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD),kfold,year,month
0,1.0,piura,piura,veintiseis de octubre,0.0,NaN,-5.163182,-80.682388,Vivienda Unifamiliar,0.0,NaN,En construcción,Costos o reposición (directo),62.50,27.58,25278,1,2020,2
1,1.0,lima,lima,surquillo,1.0,0.0,-12.115286,-77.003768,Departamento,1.0,NaN,Bueno,Comparación de mercado (directo),9.32,57.47,110807,1,2019,5

In [324]:
final_predictions = []
for fold in range(5):
    xtrain =  df[df.kfold != fold].reset_index(drop=True)
    xvalid = df[df.kfold == fold].reset_index(drop=True)
    #xtest = df_test.copy()

    ytrain = xtrain['Valor comercial (USD)']
    yvalid = xvalid['Valor comercial (USD)']
    
    xtrain = xtrain[useful_features]
    xvalid = xvalid[useful_features]
    
    ordinal_encoder = OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value=999)
    xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
    xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])
    #xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
    
    #scaler = preprocessing.StandardScaler()
    #xtrain[numerical_cols] = scaler.fit_transform(xtrain[numerical_cols])
    #xvalid[numerical_cols] = scaler.transform(xvalid[numerical_cols])
    #xtest[numerical_cols] = scaler.transform(xtest[numerical_cols])
    
    model = XGBRegressor(random_state=fold, n_jobs=-1)
    model.fit(xtrain, ytrain)
    preds_valid = model.predict(xvalid)
    #test_preds = model.predict(xtest)
    #final_predictions.append(test_preds)
    print(fold, mean_squared_error(yvalid, preds_valid, squared=False))

0 527654.2845979505
1 544220.8449826573
2 382603.7256537003
3 470184.5040861162
4 762824.9353225358

In [403]:
yvalid.values.mean() * 100

40813291.765258215

In [404]:
pred_dummy = [yvalid.values.mean()] * len(xvalid)
mean_squared_error(yvalid, pred_dummy)

1754075324883.495

In [405]:
mean_absolute_percentage_error(yvalid, pred_dummy)

3.4904078442786237

In [311]:
import optuna

In [331]:
def run(trial):
    fold = 0
    learning_rate = trial.suggest_float("learning_rate", 1e-2, 0.25, log=True)
    reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
    reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
    subsample = trial.suggest_float("subsample", 0.1, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.1, 1.0)
    max_depth = trial.suggest_int("max_depth", 1, 7)

    xtrain = df[df.kfold != fold].reset_index(drop=True)
    xvalid = df[df.kfold == fold].reset_index(drop=True)

    ytrain = xtrain['Valor comercial (USD)']
    yvalid = xvalid['Valor comercial (USD)']

    xtrain = xtrain[useful_features]
    xvalid = xvalid[useful_features]

    ordinal_encoder = preprocessing.OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value=999)
    xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
    xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])

    model = XGBRegressor(
        random_state=42,
        tree_method="gpu_hist",
        gpu_id=0,
        predictor="gpu_predictor",
        n_estimators=7000,
        learning_rate=learning_rate,
        reg_lambda=reg_lambda,
        reg_alpha=reg_alpha,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        max_depth=max_depth,
    )
    model.fit(xtrain, ytrain, early_stopping_rounds=300, eval_set=[(xvalid, yvalid)], verbose=1000)
    preds_valid = model.predict(xvalid)
    rmse = mean_squared_error(yvalid, preds_valid, squared=False)
    return rmse

In [332]:
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(action='ignore', category=UserWarning, module='/usr/local/lib/python3.6/dist-packages/optuna/*')

In [333]:
study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=30)

[I 2022-10-23 10:24:56,022] A new study created in memory with name: no-name-f0090889-b3d1-4c0b-b53c-19d65be7c074

[0]	validation_0-rmse:1047726.71897

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:655602.60736
[2000]	validation_0-rmse:646051.35665
[3000]	validation_0-rmse:643354.96709
[4000]	validation_0-rmse:641632.89430
[5000]	validation_0-rmse:641109.23806
[5750]	validation_0-rmse:640938.72309

[I 2022-10-23 10:25:05,428] Trial 0 finished with value: 640803.3203768233 and parameters: {'learning_rate': 0.07162898828407979, 'reg_lambda': 3.695132361809351, 'reg_alpha': 4.22121848546321e-08, 'subsample': 0.9751240770847359, 'colsample_bytree': 0.10680415113056448, 'max_depth': 1}. Best is trial 0 with value: 640803.3203768233.

[0]	validation_0-rmse:1055240.34992

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:650326.48345
[2000]	validation_0-rmse:646825.23719
[3000]	validation_0-rmse:645626.72501
[3119]	validation_0-rmse:645462.70677

[I 2022-10-23 10:25:10,521] Trial 1 finished with value: 645069.9872535231 and parameters: {'learning_rate': 0.017324403565253166, 'reg_lambda': 1.515617195797969e-07, 'reg_alpha': 31.6463912611683, 'subsample': 0.598112853154122, 'colsample_bytree': 0.4207784643411756, 'max_depth': 1}. Best is trial 0 with value: 640803.3203768233.

[0]	validation_0-rmse:1049094.86636

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:568258.13591
[1163]	validation_0-rmse:566489.76815

[I 2022-10-23 10:25:13,212] Trial 2 finished with value: 564679.7150286735 and parameters: {'learning_rate': 0.014326968125386008, 'reg_lambda': 0.007563151621970489, 'reg_alpha': 3.6237781910547295e-05, 'subsample': 0.42989231714946075, 'colsample_bytree': 0.7229985030294709, 'max_depth': 3}. Best is trial 2 with value: 564679.7150286735.

[0]	validation_0-rmse:1044377.08108

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:489253.21781
[2000]	validation_0-rmse:478048.46116
[3000]	validation_0-rmse:474321.07530
[4000]	validation_0-rmse:472964.13774
[4893]	validation_0-rmse:472089.02524

[I 2022-10-23 10:25:40,157] Trial 3 finished with value: 472000.75655937113 and parameters: {'learning_rate': 0.02181383969231645, 'reg_lambda': 5.92272184104026e-08, 'reg_alpha': 70.90618465218031, 'subsample': 0.26300416062160326, 'colsample_bytree': 0.6646855893963243, 'max_depth': 6}. Best is trial 3 with value: 472000.75655937113.

[0]	validation_0-rmse:1049742.66031

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:482130.20270
[2000]	validation_0-rmse:470119.41036
[3000]	validation_0-rmse:466458.16858
[4000]	validation_0-rmse:465282.20251
[5000]	validation_0-rmse:464384.74265
[5367]	validation_0-rmse:464446.30819

[I 2022-10-23 10:26:27,626] Trial 4 finished with value: 464318.33842745645 and parameters: {'learning_rate': 0.012163481960306024, 'reg_lambda': 0.00031532429477460394, 'reg_alpha': 0.0005475893025039463, 'subsample': 0.43811373465275716, 'colsample_bytree': 0.6896793950093332, 'max_depth': 7}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1021374.82713

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:481514.84186
[2000]	validation_0-rmse:477486.67686
[2704]	validation_0-rmse:476768.80334

[I 2022-10-23 10:26:39,173] Trial 5 finished with value: 476460.8451047539 and parameters: {'learning_rate': 0.059279053220222026, 'reg_lambda': 2.1115331265729735e-05, 'reg_alpha': 0.00010407014368987833, 'subsample': 0.6233408434519921, 'colsample_bytree': 0.9339043646454634, 'max_depth': 5}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1055233.83681

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:671886.70731
[2000]	validation_0-rmse:644427.74229
[3000]	validation_0-rmse:641153.74071
[4000]	validation_0-rmse:639654.68657
[4676]	validation_0-rmse:639603.22508

[I 2022-10-23 10:26:53,292] Trial 6 finished with value: 638370.9586737212 and parameters: {'learning_rate': 0.018171483061724846, 'reg_lambda': 2.4997637115214097e-07, 'reg_alpha': 1.4745604550376992e-08, 'subsample': 0.18835669733883587, 'colsample_bytree': 0.10590056960234498, 'max_depth': 5}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1054201.41712

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:603543.44029
[2000]	validation_0-rmse:593952.30160
[2308]	validation_0-rmse:598847.75451

[I 2022-10-23 10:26:57,950] Trial 7 finished with value: 593792.3672924249 and parameters: {'learning_rate': 0.024330987869194826, 'reg_lambda': 3.6550617164727945e-08, 'reg_alpha': 3.299157879797204e-05, 'subsample': 0.5133560611977435, 'colsample_bytree': 0.3249070108271052, 'max_depth': 2}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1045478.17658

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:481337.50595
[2000]	validation_0-rmse:476205.33311
[3000]	validation_0-rmse:475436.97002
[3261]	validation_0-rmse:475437.86219

[I 2022-10-23 10:27:31,581] Trial 8 finished with value: 475304.17137815186 and parameters: {'learning_rate': 0.01913796160666657, 'reg_lambda': 3.70632142542269e-05, 'reg_alpha': 1.146511724235964, 'subsample': 0.6498983583126409, 'colsample_bytree': 0.9261700333427992, 'max_depth': 7}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1049516.88514

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:483373.24627
[2000]	validation_0-rmse:477849.94125
[3000]	validation_0-rmse:475572.54032
[3236]	validation_0-rmse:475741.28585

[I 2022-10-23 10:27:59,335] Trial 9 finished with value: 475455.6025041789 and parameters: {'learning_rate': 0.05151126749959861, 'reg_lambda': 5.7008119795167894e-08, 'reg_alpha': 0.07268252367810678, 'subsample': 0.2738665421330725, 'colsample_bytree': 0.37386744244916803, 'max_depth': 7}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:928188.60826

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[873]	validation_0-rmse:496281.87265

[I 2022-10-23 10:28:02,138] Trial 10 finished with value: 494540.7458958611 and parameters: {'learning_rate': 0.21729160282971258, 'reg_lambda': 0.05742323761540139, 'reg_alpha': 0.00794940589454555, 'subsample': 0.8102629626268673, 'colsample_bytree': 0.7359382767320775, 'max_depth': 4}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1050641.45520

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:499496.93343
[2000]	validation_0-rmse:484017.60738
[3000]	validation_0-rmse:476415.46922
[4000]	validation_0-rmse:472835.57056
[5000]	validation_0-rmse:470636.35737
[6000]	validation_0-rmse:469304.92485
[6999]	validation_0-rmse:468520.09634

[I 2022-10-23 10:28:41,411] Trial 11 finished with value: 468512.5493785587 and parameters: {'learning_rate': 0.010755403798043642, 'reg_lambda': 1.8186247601752335e-05, 'reg_alpha': 63.73051386634352, 'subsample': 0.33799108206059886, 'colsample_bytree': 0.645627458766696, 'max_depth': 6}. Best is trial 4 with value: 464318.33842745645.

[0]	validation_0-rmse:1051208.98918

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:495121.96496
[2000]	validation_0-rmse:477318.97710
[3000]	validation_0-rmse:469103.97090
[4000]	validation_0-rmse:465021.20674
[5000]	validation_0-rmse:462722.57092
[6000]	validation_0-rmse:461563.54068
[6999]	validation_0-rmse:460041.67352

[I 2022-10-23 10:29:21,728] Trial 12 finished with value: 460040.6675284651 and parameters: {'learning_rate': 0.01054855674896146, 'reg_lambda': 0.00010585542029654133, 'reg_alpha': 0.002712777026544589, 'subsample': 0.4406906372876417, 'colsample_bytree': 0.5543613854568992, 'max_depth': 6}. Best is trial 12 with value: 460040.6675284651.

[0]	validation_0-rmse:1052037.65618

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:526696.48699
[2000]	validation_0-rmse:509927.08397
[3000]	validation_0-rmse:500830.78077
[3181]	validation_0-rmse:500495.91742

[I 2022-10-23 10:29:42,255] Trial 13 finished with value: 499657.18585446826 and parameters: {'learning_rate': 0.01000437292531968, 'reg_lambda': 0.000651859111618007, 'reg_alpha': 0.004953508573674836, 'subsample': 0.11101440204557023, 'colsample_bytree': 0.519005999914587, 'max_depth': 7}. Best is trial 12 with value: 460040.6675284651.

[0]	validation_0-rmse:1035643.47095

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:467477.22896
[2000]	validation_0-rmse:457553.73278
[3000]	validation_0-rmse:455576.56664
[4000]	validation_0-rmse:454430.65462
[4159]	validation_0-rmse:454287.90556

[I 2022-10-23 10:30:06,227] Trial 14 finished with value: 454202.03208447684 and parameters: {'learning_rate': 0.03603237447704198, 'reg_lambda': 0.501714691983972, 'reg_alpha': 0.00035485549705983497, 'subsample': 0.43412798997807533, 'colsample_bytree': 0.5549720002191517, 'max_depth': 6}. Best is trial 14 with value: 454202.03208447684.

[0]	validation_0-rmse:1040964.18161

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:488115.11062
[2000]	validation_0-rmse:476179.72477
[3000]	validation_0-rmse:471784.02777
[4000]	validation_0-rmse:469699.25644
[5000]	validation_0-rmse:466543.87086
[5254]	validation_0-rmse:466886.06695

[I 2022-10-23 10:30:25,583] Trial 15 finished with value: 466502.8346605344 and parameters: {'learning_rate': 0.0334397867617128, 'reg_lambda': 16.73925282660943, 'reg_alpha': 1.0599396858431485e-06, 'subsample': 0.3969014379326147, 'colsample_bytree': 0.5290254868981632, 'max_depth': 5}. Best is trial 14 with value: 454202.03208447684.

[0]	validation_0-rmse:1042701.49428

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:476978.82135
[2000]	validation_0-rmse:467709.46865
[2532]	validation_0-rmse:466887.73145

[I 2022-10-23 10:30:32,829] Trial 16 finished with value: 466047.2365125105 and parameters: {'learning_rate': 0.10254993869949791, 'reg_lambda': 0.40275682268884433, 'reg_alpha': 0.1935196078335276, 'subsample': 0.7572984241431415, 'colsample_bytree': 0.2587744648792641, 'max_depth': 4}. Best is trial 14 with value: 454202.03208447684.

[0]	validation_0-rmse:1035468.30375

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:484665.42639
[2000]	validation_0-rmse:478017.30388
[3000]	validation_0-rmse:475878.51302
[3685]	validation_0-rmse:475667.70185

[I 2022-10-23 10:30:54,111] Trial 17 finished with value: 475572.6450516302 and parameters: {'learning_rate': 0.034773799324222705, 'reg_lambda': 0.01946511968737853, 'reg_alpha': 4.030749855998533e-06, 'subsample': 0.5434708682835299, 'colsample_bytree': 0.47955863120347497, 'max_depth': 6}. Best is trial 14 with value: 454202.03208447684.

[0]	validation_0-rmse:995849.52284

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:539383.59826
[1107]	validation_0-rmse:539953.53582

[I 2022-10-23 10:30:56,731] Trial 18 finished with value: 537370.3492991772 and parameters: {'learning_rate': 0.12985153871697402, 'reg_lambda': 54.56367662148286, 'reg_alpha': 0.0006284185184877026, 'subsample': 0.725616007097881, 'colsample_bytree': 0.8204945035133904, 'max_depth': 3}. Best is trial 14 with value: 454202.03208447684.
/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-rmse:1033760.64659
[1000]	validation_0-rmse:457796.11440
[2000]	validation_0-rmse:448611.85863
[3000]	validation_0-rmse:446519.54662
[4000]	validation_0-rmse:444800.59228
[4718]	validation_0-rmse:444420.48279

[I 2022-10-23 10:31:24,072] Trial 19 finished with value: 444328.7335132292 and parameters: {'learning_rate': 0.034029634377549106, 'reg_lambda': 0.32783621575248806, 'reg_alpha': 6.955399745041692e-07, 'subsample': 0.33424127608877513, 'colsample_bytree': 0.5877130965661136, 'max_depth': 6}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1037340.76406

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:491838.43629
[2000]	validation_0-rmse:479261.91009
[3000]	validation_0-rmse:475563.35663
[3982]	validation_0-rmse:474240.80141

[I 2022-10-23 10:31:40,913] Trial 20 finished with value: 473920.2667148246 and parameters: {'learning_rate': 0.037041458790521904, 'reg_lambda': 1.9095457931058712, 'reg_alpha': 2.256131418869386e-07, 'subsample': 0.30042974480283835, 'colsample_bytree': 0.8246310448133642, 'max_depth': 5}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1039143.71695

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:474340.80554
[2000]	validation_0-rmse:466021.00511
[3000]	validation_0-rmse:464571.86951
[4000]	validation_0-rmse:463624.59289
[4489]	validation_0-rmse:463535.67036

[I 2022-10-23 10:32:07,106] Trial 21 finished with value: 463291.1950986067 and parameters: {'learning_rate': 0.029694597082059994, 'reg_lambda': 0.13561655856677585, 'reg_alpha': 4.864846120592476e-06, 'subsample': 0.471910659103498, 'colsample_bytree': 0.589310756044257, 'max_depth': 6}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1008352.11427

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:493139.77494
[1853]	validation_0-rmse:491085.31063

[I 2022-10-23 10:32:17,997] Trial 22 finished with value: 490386.1071295294 and parameters: {'learning_rate': 0.07273460984023593, 'reg_lambda': 0.00354326410535803, 'reg_alpha': 0.004012563430933202, 'subsample': 0.38827052630302117, 'colsample_bytree': 0.590316109696178, 'max_depth': 6}. Best is trial 19 with value: 444328.7335132292.
/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-rmse:1050981.75752
[1000]	validation_0-rmse:497667.67679
[2000]	validation_0-rmse:488922.22733
[2063]	validation_0-rmse:487865.23173

[I 2022-10-23 10:32:25,679] Trial 23 finished with value: 487809.80952604464 and parameters: {'learning_rate': 0.04415803674366942, 'reg_lambda': 2.725212957500994e-06, 'reg_alpha': 0.044352138267658825, 'subsample': 0.21958620725039038, 'colsample_bytree': 0.45396613676451675, 'max_depth': 5}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1041496.74193

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:480675.34914
[2000]	validation_0-rmse:469144.24712
[3000]	validation_0-rmse:464621.61040
[4000]	validation_0-rmse:463123.59709
[4841]	validation_0-rmse:462230.84190

[I 2022-10-23 10:32:52,934] Trial 24 finished with value: 462142.9660880282 and parameters: {'learning_rate': 0.027804224401843824, 'reg_lambda': 1.061708707063878, 'reg_alpha': 1.237975291820333, 'subsample': 0.3474236233016214, 'colsample_bytree': 0.5940791981434281, 'max_depth': 6}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:995045.43983

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:519348.75756
[1356]	validation_0-rmse:519194.88503

[I 2022-10-23 10:32:57,097] Trial 25 finished with value: 517354.9602776846 and parameters: {'learning_rate': 0.10386155641623801, 'reg_lambda': 9.825999827774874e-05, 'reg_alpha': 0.0001804014178084763, 'subsample': 0.5040984586815286, 'colsample_bytree': 0.8016578989830385, 'max_depth': 4}. Best is trial 19 with value: 444328.7335132292.
/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-rmse:1055661.95393
[1000]	validation_0-rmse:510270.21922
[2000]	validation_0-rmse:497380.93555
[3000]	validation_0-rmse:490105.14166
[4000]	validation_0-rmse:486877.58494
[5000]	validation_0-rmse:484096.69952
[5130]	validation_0-rmse:483943.72173

[I 2022-10-23 10:33:34,228] Trial 26 finished with value: 483649.5218706273 and parameters: {'learning_rate': 0.013980576926344638, 'reg_lambda': 0.0026526292717149952, 'reg_alpha': 3.3456131985354554e-07, 'subsample': 0.15782564116104952, 'colsample_bytree': 0.3325871967228818, 'max_depth': 7}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1051236.07453

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:500244.59796
[2000]	validation_0-rmse:488937.01970
[3000]	validation_0-rmse:482317.15481
[3154]	validation_0-rmse:482579.44726

[I 2022-10-23 10:33:46,101] Trial 27 finished with value: 481912.6037884821 and parameters: {'learning_rate': 0.04323479461567938, 'reg_lambda': 0.07616017795548734, 'reg_alpha': 2.6974852944654586e-05, 'subsample': 0.35744852431205565, 'colsample_bytree': 0.2413231950300455, 'max_depth': 5}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:941416.34605

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:531499.40509
[1072]	validation_0-rmse:533773.22371

[I 2022-10-23 10:33:48,671] Trial 28 finished with value: 528028.7855382083 and parameters: {'learning_rate': 0.20258962867976546, 'reg_lambda': 9.332940058141811e-07, 'reg_alpha': 0.0020058916206177058, 'subsample': 0.46296240834520797, 'colsample_bytree': 0.5208561735658347, 'max_depth': 3}. Best is trial 19 with value: 444328.7335132292.

[0]	validation_0-rmse:1047617.89115

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:465122.84560
[2000]	validation_0-rmse:457382.28451
[3000]	validation_0-rmse:454558.77726
[3608]	validation_0-rmse:454362.78173

[I 2022-10-23 10:34:09,234] Trial 29 finished with value: 454250.4178686653 and parameters: {'learning_rate': 0.06331610627717717, 'reg_lambda': 9.484160114309013, 'reg_alpha': 1.2096555733284028e-07, 'subsample': 0.8430520321889725, 'colsample_bytree': 0.41893032338795816, 'max_depth': 6}. Best is trial 19 with value: 444328.7335132292.

In [334]:
study.best_params

{'learning_rate': 0.034029634377549106,
 'reg_lambda': 0.32783621575248806,
 'reg_alpha': 6.955399745041692e-07,
 'subsample': 0.33424127608877513,
 'colsample_bytree': 0.5877130965661136,
 'max_depth': 6}

In [335]:
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error

In [342]:
final_predictions = []
final_valid = []
scores = []
mapes = []
for fold in range(5):
    xtrain =  df[df.kfold != fold].reset_index(drop=True)
    xvalid = df[df.kfold == fold].reset_index(drop=True)
    #xtest = df_test.copy()

    ytrain = xtrain['Valor comercial (USD)']
    yvalid = xvalid['Valor comercial (USD)']
    
    xtrain = xtrain[useful_features]
    xvalid = xvalid[useful_features]
    
    ordinal_encoder = preprocessing.OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value=999)
    xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
    xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])
    #xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
    
    params = {'learning_rate': 0.034029634377549106,
             'reg_lambda': 0.32783621575248806,
             'reg_alpha': 6.955399745041692e-07,
             'subsample': 0.33424127608877513,
             'colsample_bytree': 0.5877130965661136,
             'max_depth': 6}
    
    model = XGBRegressor(
        random_state=0, 
        tree_method='gpu_hist',
        gpu_id=0,
        predictor="gpu_predictor",
        n_estimators=5000,
        **params
    )
    model.fit(xtrain, ytrain, early_stopping_rounds=300, eval_set=[(xvalid, yvalid)], verbose=1000)
    preds_valid = model.predict(xvalid)
    final_valid.append(preds_valid)
    #test_preds = model.predict(xtest)
    #final_predictions.append(test_preds)
    rmse = mean_squared_error(yvalid, preds_valid, squared=False)
    maperror = mean_absolute_percentage_error(yvalid, preds_valid)
    print(fold, rmse, maperror)
    scores.append(rmse)
    mapes.append(maperror)

print(np.mean(scores), np.std(scores), np.mean(mapes), np.std(mapes))

[0]	validation_0-rmse:1034919.74343

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:461079.26062
[2000]	validation_0-rmse:452389.42915
[2366]	validation_0-rmse:451789.49117
0 451754.7620899899 0.7200291946002433
[0]	validation_0-rmse:1230265.59496

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:582860.52456
[2000]	validation_0-rmse:574246.33568
[3000]	validation_0-rmse:571847.66922
[4000]	validation_0-rmse:570092.19878
[4999]	validation_0-rmse:569370.10177
1 569346.252210583 0.8796300646818636
[0]	validation_0-rmse:925604.43604

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:416320.21649
[2000]	validation_0-rmse:410267.32706
[3000]	validation_0-rmse:407569.36749
[4000]	validation_0-rmse:406393.95901
[4418]	validation_0-rmse:406263.90594
2 406077.8159460652 1.331670836488896
[0]	validation_0-rmse:1035190.74425

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:471169.84736
[2000]	validation_0-rmse:466958.03653
[3000]	validation_0-rmse:464943.09400
[3204]	validation_0-rmse:465530.26046
3 464655.50292857824 0.6676693471206039
[0]	validation_0-rmse:1366472.13282

/home/hydroinfmtk/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/xgboost/sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[1000]	validation_0-rmse:687719.37508
[2000]	validation_0-rmse:679065.19124
[3000]	validation_0-rmse:676524.55336
[4000]	validation_0-rmse:675067.34277
[4155]	validation_0-rmse:675164.10588
4 674964.5684416963 0.6798143487546282
513359.7803233826 96878.58108569104 0.8557627583292469 0.2497273399788887

In [349]:
ypred = model.predict(xvalid)

In [352]:
ypred

array([ 50746.97 , 115178.25 , 184580.61 , ...,  46618.363,  27251.332,
        55247.887], dtype=float32)

In [370]:
valid_DF = pd.DataFrame({'yvalid': yvalid, 'ypred':ypred})
valid_DF['ypred'] = valid_DF['ypred'].astype(int)
valid_DF['diff_perc'] = (yvalid - ypred)/yvalid*100

In [374]:
valid_DF.iloc[:100,:]

    yvalid   ypred  diff_perc
0    42285   50746 -20.011751
1   104716  115178  -9.991071
2   177981  184580  -3.708042
3    84774   63265  25.371217
4   148800  186913 -25.614226
..     ...     ...        ...
95  267571  242539   9.355005
96  116704  137898 -18.160622
97  404407  407349  -0.727678
98  158000  134290  15.005864
99   69606   79500 -14.215560

[100 rows x 3 columns]

In [506]:
abs(valid_DF['diff_perc']).mean()

67.98143487546281

In [408]:
valid_DF['diff_perc'].sort_values(ascending=True)[:100]

7560    -112280.571619
3360     -72615.404391
5334     -14646.668865
10512     -9681.637076
7007      -8619.868249
             ...
5001       -598.353863
2013       -597.918581
5519       -588.977301
1909       -581.512210
7148       -568.187440
Name: diff_perc, Length: 100, dtype: float64

In [379]:
valid_DF.loc[3507, :]

yvalid         7308.0000
ypred       -262957.0000
diff_perc      3698.2207
Name: 3507, dtype: float64

In [385]:
valid_DF['diff_perc'].sort_values().hist?

Docstring: Alias for `%history`.
File:      ~/mambaforge/envs/ml-zoomcamp/lib/python3.9/site-packages/IPython/core/magic.py

In [392]:
np.abs(valid_DF['diff_perc']).mean()

67.98143487546281

In [494]:
test = pd.read_excel('data/data_test_final equipos consolidado.xlsx')

In [495]:
test.head()

,ID,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),...,Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2014-06-07,4.0,NaN,Lima,Lima,Surquillo,0.0,0.0,-12.115050,...,Departamento,NaN,NaN,1.0,NaN,Muy bueno,Comparación de mercado (directo),9.03,78.48,NaN
1,2,2015-09-11,1.0,NaN,Lima,Lima,La Molina,1.0,0.0,-12.067776,...,Departamento,NaN,NaN,15.0,NaN,Bueno,Comparación de mercado (directo),49.89,119.55,NaN
2,3,2015-09-11,1.0,NaN,Lima,Lima,La Molina,1.0,0.0,-12.068426,...,Terreno Urbano,NaN,NaN,13.0,NaN,Bueno,Comparación de mercado (directo),45.11,83.69,NaN
3,4,2015-09-12,3.0,NaN,Lima,Lima,Santiago de Surco,0.0,2.0,-12.135344,...,Departamento,NaN,NaN,22.0,NaN,NaN,Comparación de mercado (directo),84.81,165.40,NaN
4,5,2015-12-21,2.0,NaN,Lima,Lima,San Juan de Miraflores,0.0,1.0,-12.149818,...,Departamento,NaN,NaN,47.0,NaN,NaN,Comparación de mercado (directo),38.28,113.57,NaN

In [496]:
test.isnull().sum()

ID                               0
Fecha entrega del Informe        0
Tipo de vía                   1713
Piso                         16179
Departamento                     0
Provincia                        0
Distrito                         0
Número de estacionamiento     3834
Depósitos                     5372
Latitud (Decimal)               28
Longitud (Decimal)              44
Categoría del bien               0
Posición                     13627
Número de frentes            14666
Edad                          1429
Elevador                     13516
Estado de conservación        4025
Método Representado            316
Área Terreno                  1437
Área Construcción             1177
Valor comercial (USD)        16940
dtype: int64

In [497]:
test.columns

Index(['ID', 'Fecha entrega del Informe', 'Tipo de vía', 'Piso',
       'Departamento', 'Provincia', 'Distrito', 'Número de estacionamiento',
       'Depósitos', 'Latitud (Decimal)', 'Longitud (Decimal)',
       'Categoría del bien', 'Posición', 'Número de frentes', 'Edad',
       'Elevador', 'Estado de conservación', 'Método Representado',
       'Área Terreno', 'Área Construcción', 'Valor comercial (USD)'],
      dtype='object')

In [498]:
def transformdf(df):
    
    df.drop(columns=['Piso', 'Posición', 'Número de frentes', 'Valor comercial (USD)'], axis=1, inplace=True)
    df['year'] = df['Fecha entrega del Informe'].dt.year
    df['month'] = df['Fecha entrega del Informe'].dt.month
    df.drop(columns='Fecha entrega del Informe', axis=1, inplace=True)

    
    df['Área Terreno'] = df['Área Terreno'].apply(lambda x: str(x).replace(',', '')) 
    df['Área Construcción'] = df['Área Construcción'].apply(lambda x: str(x).replace(',', '')) 
    df['Área Terreno'] = pd.to_numeric(df['Área Terreno'], errors='coerce')
    df['Área Construcción'] = pd.to_numeric(df['Área Construcción'], errors='coerce')
    
    df['Departamento'] = df['Departamento'].apply(lambda x: str(x).lower()) 
    df['Provincia'] = df['Provincia'].apply(lambda x: str(x).lower()) 
    df['Distrito'] = df['Distrito'].apply(lambda x: str(x).lower())
    
    df['Departamento'] = df['Departamento'].apply(strip_accents) 
    df['Provincia'] = df['Provincia'].apply(strip_accents) 
    df['Distrito'] = df['Distrito'].apply(strip_accents)
    
    df["Tipo de vía"].fillna(0, inplace = True)
    df["Número de estacionamiento"].fillna(0, inplace = True)
    df["Número de estacionamiento"].fillna(0, inplace = True)
    dist_coord_lost = df[((df['Latitud (Decimal)'].isnull() == True) | (df['Longitud (Decimal)'].isnull() == True)) == True]
    mask_idx = list(dist_coord_lost.index)
    for i in mask_idx:
        distrito = df.loc[i, 'Distrito']
        provincia = df.loc[i, 'Provincia']

        if distrito in dist_sh:
            df.loc[i, 'Latitud (Decimal)'] = (distritos_cent.loc[distritos_cent['NOMBDIST'] == distrito, 'lat_cent']).values[0]
            df.loc[i, 'Longitud (Decimal)'] = (distritos_cent.loc[distritos_cent['NOMBDIST'] == distrito, 'lon_cent']).values[0]
        elif provincia in prov_sh:
            df.loc[i, 'Latitud (Decimal)'] = (provincia_cent.loc[provincia_cent['NOMBPROV'] == provincia, 'lat_cent']).values[0]
            df.loc[i, 'Longitud (Decimal)'] = (provincia_cent.loc[provincia_cent['NOMBPROV'] == provincia, 'lon_cent']).values[0]
        else:
            df.loc[i, 'Latitud (Decimal)'] = -9.19
            df.loc[i, 'Longitud (Decimal)'] = -75.016
    
    
    Edad = []
    for i in df["Edad"]:
      if i > 1600:
        Edad.append(2022-i)
      else:
        Edad.append(i)
    df['Edad'] = Edad
    df["Edad"].fillna(np.mean(df["Edad"]), inplace = True)
    df['Categoría del bien'].fillna('Otro', inplace = True)
    dtype0 = {'Tipo de vía': 'category',
                            'Departamento': 'category',
                            'Provincia': 'category',
                            'Distrito': 'category',
                            'Categoría del bien': 'category',
                            'Estado de conservación': 'category',
                            'Método Representado': 'category'}
    df =df.astype(dtype0)
    object_cols = ['Tipo de vía', 'Departamento', 'Provincia', 'Distrito', 'Categoría del bien', 'Estado de conservación', 'Método Representado']
    
    xtest = df[useful_features]
    xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
    
    return xtest

In [499]:
test_df = transformdf(test)
test_df.head()

/tmp/ipykernel_22071/4077073112.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])

,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,year,month
0,4.0,13.0,76.0,402.0,0.0,0.0,-12.115050,-77.008261,3.0,1.0,NaN,5.0,0.0,9.03,78.48,2014,6
1,1.0,13.0,76.0,196.0,1.0,0.0,-12.067776,-76.965110,3.0,15.0,NaN,0.0,0.0,49.89,119.55,2015,9
2,1.0,13.0,76.0,196.0,1.0,0.0,-12.068426,-76.963140,15.0,13.0,NaN,0.0,0.0,45.11,83.69,2015,9
3,3.0,13.0,76.0,385.0,0.0,2.0,-12.135344,-76.983677,3.0,22.0,NaN,NaN,0.0,84.81,165.40,2015,9
4,2.0,13.0,76.0,358.0,0.0,1.0,-12.149818,-76.974677,3.0,47.0,NaN,NaN,0.0,38.28,113.57,2015,12

In [500]:
ytest_pred = model.predict(test_df)

In [504]:
len(ytest_pred)

16940

In [503]:
list(ytest_pred)

[132835.14,
 165861.66,
 180780.95,
 269470.8,
 83297.37,
 189573.64,
 698248.6,
 42828.656,
 429580.53,
 158296.17,
 69269.69,
 147403.78,
 244640.67,
 642524.44,
 745200.75,
 546437.0,
 353957.97,
 789058.9,
 147013.9,
 741975.1,
 278900.88,
 156926.03,
 66957.55,
 2957293.8,
 1275273.1,
 107431.484,
 266595.12,
 3553844.8,
 190267.72,
 330846.06,
 129585.75,
 189571.4,
 2727762.8,
 514932.7,
 230394.3,
 134332.77,
 224201.94,
 799993.4,
 346518.53,
 28104.564,
 259932.66,
 87865.16,
 286450.9,
 302480.06,
 200987.42,
 21095.36,
 466618.6,
 134907.4,
 533026.0,
 220088.3,
 302094.62,
 1107767.5,
 175304.62,
 45366.023,
 82166.84,
 142974.06,
 162709.8,
 121158.89,
 206400.72,
 461794.44,
 74914.78,
 666719.1,
 273112.0,
 51384.156,
 75335.73,
 82767.984,
 102029.734,
 273908.2,
 125170.32,
 172436.6,
 61070.797,
 204734.9,
 130246.625,
 1245933.0,
 247533.44,
 364964.2,
 122561.555,
 312849.47,
 50880.44,
 81349.17,
 147931.72,
 30705.781,
 442366.88,
 633426.1,
 476123.3,
 190605.7,
 509009.25,
 306444.2,
 206225.25,
 251391.9,
 3429049.0,
 159370.44,
 286984.9,
 198161.42,
 169154.44,
 395909.9,
 19422.232,
 576761.56,
 474870.03,
 326387.28,
 1435536.8,
 66411.22,
 180496.84,
 505271.88,
 164897.64,
 235559.73,
 338357.38,
 59980.52,
 1223471.1,
 229616.16,
 -43393.113,
 128030.74,
 159877.5,
 562044.44,
 197944.08,
 792538.9,
 545800.3,
 124459.75,
 229128.14,
 523626.25,
 41424.97,
 310972.0,
 80363.77,
 283292.47,
 723618.94,
 241977.25,
 154459.16,
 143155.75,
 263727.25,
 247186.2,
 175835.42,
 81170.164,
 223122.89,
 110802.17,
 582717.2,
 115523.016,
 48833.1,
 279517.94,
 7878069.0,
 1759270.0,
 409259.7,
 324491.4,
 686365.6,
 237207.1,
 300212.94,
 232236.16,
 306134.56,
 165343.03,
 73506.805,
 568957.5,
 1568995.4,
 180316.97,
 303898.5,
 181252.95,
 379607.62,
 153734.6,
 56137.727,
 25961.818,
 25961.818,
 2218349.0,
 154238.12,
 116664.89,
 297713.0,
 54946.387,
 68475.68,
 128008.07,
 399709.8,
 1012631.4,
 -20331.432,
 442172.7,
 64039.0,
 116774.0,
 35593.09,
 749604.56,
 294010.9,
 1453818.5,
 652145.4,
 990071.1,
 54757.94,
 231198.17,
 3563589.0,
 156509.1,
 138841.94,
 57067.293,
 162113.45,
 170158.03,
 9136.875,
 463067.56,
 96371.42,
 128507.13,
 127179.484,
 323708.97,
 85579.11,
 149465.16,
 68849.02,
 422500.66,
 2046837.1,
 320961.16,
 127265.6,
 132959.48,
 214793.69,
 206050.61,
 877986.56,
 688487.0,
 202619.14,
 336916.47,
 121487.836,
 127521.68,
 59875.145,
 1440094.2,
 126543.32,
 1138522.5,
 353645.53,
 260767.47,
 127856.45,
 230534.61,
 430513.16,
 123035.76,
 259136.45,
 25096.227,
 142065.31,
 647118.8,
 266728.1,
 205746.8,
 4879.075,
 159447.81,
 108179.516,
 192982.4,
 383389.28,
 140321.03,
 94529.766,
 92217.164,
 212586.47,
 56428.383,
 54446.465,
 171130.12,
 154546.81,
 22778.883,
 34023.125,
 155991.88,
 574607.94,
 64845.77,
 325067.72,
 268510.88,
 277762.25,
 217970.22,
 131576.56,
 325622.53,
 279111.94,
 359503.94,
 149829.83,
 49665.336,
 176102.73,
 634997.06,
 773201.94,
 85838.23,
 305906.34,
 313439.53,
 124187.97,
 100876.445,
 108880.32,
 113504.3,
 102356.44,
 373018.94,
 79577.62,
 334862.84,
 720878.1,
 66656.67,
 391227.06,
 981251.0,
 950869.94,
 138357.27,
 29549.105,
 196292.58,
 147989.55,
 93046.54,
 464562.78,
 194346.75,
 129614.14,
 16885.998,
 146120.72,
 202317.19,
 126463.18,
 155053.38,
 96550.52,
 316085.03,
 802533.2,
 303913.06,
 194422.64,
 270996.88,
 37388.824,
 181795.14,
 247860.66,
 424290.53,
 578979.25,
 289402.16,
 127286.35,
 217450.2,
 19114.805,
 117956.39,
 166607.25,
 64025.227,
 101977.62,
 34149.285,
 99367.055,
 33265.79,
 145184.61,
 70225.07,
 188350.97,
 1374580.4,
 211119.77,
 145476.17,
 46781.434,
 246904.28,
 549250.4,
 59599.25,
 205815.75,
 49665.336,
 81753.99,
 118340.266,
 244225.14,
 118537.734,
 236819.89,
 130442.87,
 192674.45,
 10374.714,
 100581.45,
 201715.1,
 239243.86,
 334052.6,
 248637.72,
 235156.89,
 251103.45,
 244349.1,
 150265.48,
 2120954.8,
 170538.39,
 244320.17,
 401199.2,
 69334.88,
 132453.27,
 691054.1,
 175599.28,
 86236.914,
 1025007.1,
 147426.77,
 114024.086,
 56846.57,
 52124.74,
 591757.4,
 410794.75,
 168097.08,
 346950.25,
 380933.5,
 301896.97,
 366359.16,
 114058.98,
 240169.8,
 100189.91,
 1471522.4,
 112093.78,
 573360.06,
 400939.25,
 121133.43,
 136091.05,
 51403.5,
 122083.836,
 244391.6,
 40252.74,
 84479.46,
 785096.7,
 236253.48,
 72589.92,
 261338.7,
 71321.11,
 1253806.6,
 41902.586,
 276121.06,
 87017.086,
 213407.4,
 190333.95,
 69652.25,
 222522.02,
 5789.443,
 337148.75,
 275798.38,
 165644.44,
 656755.2,
 130775.13,
 295567.38,
 1427190.8,
 253966.61,
 327462.72,
 129198.38,
 353734.16,
 272603.7,
 112130.445,
 196758.83,
 147800.1,
 136516.94,
 136622.45,
 129271.06,
 530342.06,
 574732.1,
 412411.9,
 400276.16,
 200300.36,
 43120.277,
 112234.625,
 300730.38,
 230141.12,
 556926.75,
 252545.44,
 225220.56,
 409110.66,
 225480.73,
 225856.52,
 99090.09,
 319984.34,
 -245755.47,
 91238.41,
 84144.55,
 115064.375,
 89324.445,
 393110.62,
 195316.84,
 99612.445,
 108853.83,
 68502.5,
 218689.45,
 722524.7,
 324037.9,
 329562.4,
 87185.19,
 202747.22,
 199003.58,
 132189.7,
 28544.42,
 111352.17,
 152298.42,
 285398.47,
 530537.7,
 234055.6,
 222102.56,
 819945.1,
 2048476.1,
 220366.75,
 400252.16,
 111197.234,
 66849.664,
 186074.64,
 376368.12,
 282611.28,
 445745.9,
 190540.58,
 196998.73,
 254483.14,
 77435.44,
 101343.85,
 -58893.24,
 343028.44,
 242086.17,
 167393.56,
 72965.56,
 206747.97,
 28544.42,
 130318.25,
 574933.7,
 199194.72,
 1535417.2,
 141369.77,
 52249.656,
 40314.547,
 139513.11,
 46775.35,
 195561.83,
 159498.33,
 33557.98,
 108080.93,
 1331181.4,
 23957.434,
 228203.64,
 893637.3,
 154278.58,
 303414.6,
 92975.67,
 347498.8,
 471456.8,
 254237.62,
 110565.82,
 56298.617,
 55263.957,
 363038.44,
 410083.84,
 245224.53,
 84773.16,
 312060.47,
 94581.14,
 404921.94,
 310243.25,
 458545.0,
 80300.26,
 251902.14,
 272283.56,
 116390.234,
 137146.34,
 115032.65,
 70750.46,
 50255.51,
 29382.828,
 128527.5,
 477006.5,
 17476.836,
 264041.03,
 675282.44,
 40314.547,
 418170.8,
 153918.16,
 728391.56,
 113918.04,
 112843.54,
 56297.457,
 135152.16,
 248519.42,
 228419.47,
 65614.37,
 150869.92,
 342370.0,
 1790050.1,
 202772.27,
 14296.22,
 2534795.0,
 -7124.889,
 272687.4,
 99967.29,
 288272.28,
 107010.7,
 37943.344,
 278222.03,
 52378.652,
 253933.28,
 48348.473,
 270669.1,
 518255.22,
 144677.53,
 203544.17,
 325054.9,
 69582.4,
 235553.3,
 193317.0,
 67564.86,
 201910.23,
 46527.824,
 210937.44,
 260495.25,
 68720.23,
 2069739.4,
 176609.25,
 1630786.2,
 117639.266,
 133882.66,
 362464.5,
 489475.03,
 213071.25,
 206406.55,
 73469.336,
 461070.1,
 305874.78,
 340022.34,
 100982.805,
 77600.31,
 213694.45,
 640623.06,
 657505.56,
 200684.81,
 -378836.7,
 181496.27,
 139620.25,
 236244.48,
 96632.91,
 -92833.85,
 3089490.8,
 83969.484,
 50287.133,
 356237.9,
 203965.64,
 318387.3,
 88476.164,
 245497.28,
 149894.33,
 136616.94,
 87588.055,
 1077655.2,
 70289.2,
 203549.64,
 348202.3,
 970591.56,
 78003.555,
 44483.96,
 334844.62,
 59896.445,
 317320.28,
 7762390.0,
 230239.3,
 109924.21,
 223269.69,
 203319.28,
 343584.88,
 345714.4,
 115385.54,
 89700.54,
 1497211.4,
 2294690.2,
 149411.12,
 327285.78,
 13309.425,
 251073.19,
 9948.724,
 149777.64,
 539060.94,
 366394.97,
 79295.36,
 45340.332,
 54719.82,
 386039.3,
 12302.755,
 248862.77,
 219327.28,
 199266.44,
 344744.94,
 676561.0,
 345803.16,
 218502.86,
 13915.703,
 55178.395,
 362102.72,
 213672.05,
 297062.75,
 297353.94,
 126695.72,
 192107.58,
 175804.03,
 373857.8,
 381638.84,
 262601.94,
 165499.75,
 207974.1,
 381453.25,
 114363.91,
 129189.04,
 146504.72,
 1368456.6,
 256553.19,
 243673.52,
 2439111.8,
 48308.09,
 368331.16,
 112695.52,
 157855.72,
 61452.97,
 208104.86,
 211437.84,
 4578466.0,
 62285.492,
 738976.56,
 99802.2,
 317683.06,
 66304.58,
 564969.8,
 57168.555,
 531198.0,
 275179.22,
 17910.645,
 3125471.8,
 191088.89,
 128603.65,
 161401.06,
 75709.875,
 1570421.6,
 134446.39,
 548213.56,
 319613.06,
 310885.06,
 149333.45,
 151066.05,
 104037.914,
 449013.03,
 709526.9,
 115687.98,
 1527042.0,
 246978.31,
 49349.11,
 339310.97,
 2610.6729,
 455924.06,
 232139.2,
 747772.4,
 115338.875,
 48308.09,
 15658.856,
 90984.805,
 337053.7,
 54186.184,
 300414.84,
 227228.98,
 328738.34,
 38734.984,
 271094.34,
 388056.2,
 133318.55,
 118244.086,
 196893.98,
 87555.086,
 375780.88,
 132994.28,
 362660.34,
 346025.4,
 706519.06,
 156563.95,
 439623.9,
 71756.03,
 334585.47,
 169709.06,
 -278444.22,
 316152.4,
 145910.73,
 485779.7,
 1794229.5,
 83553.34,
 217740.95,
 104726.33,
 -35569.16,
 362514.47,
 208031.06,
 342079.53,
 1414773.2,
 239994.05,
 306607.84,
 427662.7,
 111788.59,
 133333.2,
 416531.34,
 151740.3,
 530863.8,
 238048.6,
 83059.984,
 110349.99,
 246360.03,
 189768.03,
 114162.78,
 124902.63,
 253058.62,
 244246.77,
 69457.45,
 547085.4,
 60395.832,
 57117.74,
 125219.49,
 123818.37,
 376964.88,
 306358.56,
 414491.03,
 217193.06,
 275887.3,
 1095692.4,
 30125.756,
 274021.34,
 189494.5,
 194193.45,
 267666.6,
 73495.47,
 228682.98,
 54297.094,
 294210.75,
 360867.88,
 152032.38,
 212464.66,
 307785.2,
 449978.5,
 244740.55,
 67364.07,
 73805.45,
 117195.36,
 131959.5,
 103670.32,
 344843.34,
 105111.46,
 201465.98,
 91364.87,
 69020.12,
 541272.9,
 35358.055,
 6433824.0,
 76250.32,
 501981.72,
 37774.79,
 17726.955,
 89374.46,
 283813.84,
 77259.95,
 104215.02,
 218112.83,
 155665.89,
 8144218.5,
 209184.19,
 51006.31,
 226625.75,
 598782.7,
 50479.492,
 456001.84,
 99856.81,
 1706157.1,
 56887.8,
 612448.94,
 239132.31,
 375656.84,
 177593.19,
 195845.56,
 1247345.9,
 443842.47,
 32207.924,
 98848.79,
 108970.805,
 70304.79,
 356070.38,
 101097.914,
 113654.08,
 113772.07,
 33651.812,
 -8947.492,
 229602.47,
 -21095.854,
 1364517.1,
 214757.75,
 278555.12,
 231969.97,
 129408.05,
 239095.7,
 132183.11,
 59071.99,
 215469.48,
 243708.02,
 2257369.8,
 34535.273,
 72067.914,
 279150.06,
 178440.12,
 237814.17,
 692631.94,
 119992.01,
 145661.6,
 324554.78,
 379989.16,
 84116.46,
 775973.6,
 632120.4,
 256790.36,
 737243.75,
 98852.79,
 309395.62,
 941087.75,
 96461.71,
 34535.273,
 126374.875,
 248179.81,
 234666.88,
 173047.84,
 67364.07,
 -56180.316,
 102728.73,
 98108.445,
 517145.66,
 421610.56,
 219336.94,
 146837.77,
 54640.895,
 109527.17,
 23477.992,
 1099084.8,
 967622.8,
 87925.625,
 98337.52,
 145268.94,
 74819.57,
 289453.34,
 149607.47,
 284263.72,
 715121.3,
 26979.822,
 239119.02,
 255754.61,
 94415.93,
 92762.96,
 128777.58,
 61197.914,
 647485.2,
 654099.2,
 49929.957,
 79405.35,
 576028.0,
 73768.336,
 73768.336,
 260488.92,
 433728.34,
 106449.07,
 266421.94,
 373370.0,
 44730.27,
 409670.53,
 207115.83,
 114870.4,
 195801.92,
 394540.3,
 37652.19,
 56797.78,
 118559.445,
 272467.16,
 49608.91,
 174795.66,
 107587.805,
 234517.55,
 -465.82785,
 151069.25,
 287910.53,
 115563.77,
 126732.47,
 49139.44,
 405641.44,
 48439.188,
 363285.06,
 70704.79,
 59319.145,
 267889.4,
 116660.33,
 98830.6,
 30395.43,
 420606.53,
 485191.84,
 182913.02,
 590155.0,
 496678.72,
 165735.16,
 115886.11,
 286457.44,
 535683.1,
 218545.7,
 125081.32,
 284004.44,
 712499.0,
 341431.2,
 42646.03,
 121901.234,
 67364.07,
 160976.97,
 168187.95,
 826309.7,
 151766.81,
 412946.72,
 282159.75,
 101417.25,
 67364.07,
 121137.43,
 135566.45,
 132409.62,
 124225.61,
 253639.28,
 382239.16,
 35900.11,
 356937.4,
 177291.64,
 2007432.2,
 273544.7,
 97855.95,
 414910.03,
 79981.68,
 104078.16,
 177216.73,
 149266.75,
 47633.97,
 1419860.4,
 76831.35,
 293126.3,
 413089.4,
 259029.4,
 59506.816,
 219043.42,
 114082.62,
 373317.5,
 65033.58,
 267021.16,
 157648.25,
 50619.004,
 370082.84,
 348981.06,
 108838.914,
 306636.5,
 50619.004,
 50619.004,
 237833.19,
 353614.0,
 ...]

In [ ]:
test_DF = pd.DataFrame({'yvalid': y, 'ytest_pred':ytest_pred})
test_DF['ytest_pred'] = valid_DF['ytest_pred'].astype(int)
test_DF['diff_perc'] = (yvalid - ypred)/yvalid*100

In [485]:
test_df.isnull().sum()

ID                               0
Tipo de vía                      0
Departamento                     0
Provincia                        0
Distrito                         0
Número de estacionamiento        0
Depósitos                     5372
Latitud (Decimal)                0
Longitud (Decimal)               0
Categoría del bien               0
Edad                             0
Elevador                     13516
Estado de conservación        4025
Método Representado            316
Área Terreno                  1437
Área Construcción             1177
Valor comercial (USD)        16940
year                             0
month                            0
dtype: int64